[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Forzamos el uso del Core modificado oficial de Bluepad32 en lugar del estándar
platform_packages =
    framework-arduinoespressif32@https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip

; Flags necesarias para activar el soporte Bluetooth de Bluepad32
build_flags = 
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    # Tus librerías de motores y pantalla calibrada con dirección 0x27
    teemuatlut/TMCStepper @ ^0.7.3
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
